backend:
  name: github
  repo: ohadpr/bizme-newsletter
  branch: master

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "newsletters" # Used in routes, e.g., /admin/collections/blog
    label: "Newsletters" # Used in the UI
    folder: "newsletters" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{subject}}"
    fields: 
      - {label: ID, name: id, widget: number}
      - {label: Subject, name: subject, widget: string}
      - {label: Prefix, name: prefix, widget: string}
      - name: posts
        label: Posts
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: string}
          - {label: Link, name: link, widget: string}
          - {label: Image, name: image, widget: string}
          - {label: Type, name: type, widget: select, options: ['ARTICLE', 'COMMUNITY', 'INTERVIEW', 'POLL']}
      - {label: Callout, name: callout, widget: string}
      - {label: Suffix, name: suffix, widget: string}
