backend:
  name: github
  repo: ohadpr/bizme-newsletter
  branch: master

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "templates" # Used in routes, e.g., /admin/collections/blog
    label: "Templates" # Used in the UI
    folder: "templates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
